version: "3.9"

services:
  ${ SERVICE }:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: ${ IMAGE_NAME }
    container_name: ${ CONTAINER_NAME }
    volumes:
      - type: bind
        source: ..
        target: /workspace
    #ports:
    #  - 3000:3000
    # command: 
    tty: true
    stdin_open: true
